name: Flask Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Start Streamlit app
      run: |
        nohup streamlit run streamlit-app.py &>/dev/null &
        sleep 10  # Wait for Streamlit to start

    - name: Check Streamlit app is running
      run: |
        curl --silent --fail http://localhost:8501 || exit 1

    - name: Stop Streamlit app
      run: |
        pkill -f "streamlit"